### Get all images
GET http://localhost:3000/api/images

### Get all images with token
GET http://localhost:3000/api/images
Authorization: Bearer REPLACE_WITH_JWT

### Get one image by ID with token
GET http://localhost:3000/api/images/69ace105da34209d3166e9f6
Authorization: Bearer REPLACE_WITH_JWT

### Rename image with token (204 if owner, 403 if not owner)
PATCH http://localhost:3000/api/images/69ace105da34209d3166e9f6
Content-Type: application/json
Authorization: Bearer REPLACE_WITH_JWT

{
  "name": "Sheepdog herding a sheep"
}

### Rename image without token
PATCH http://localhost:3000/api/images/69ace105da34209d3166e9f6
Content-Type: application/json

{
  "name": "i am going to fail!"
}

### Rename image with non-owner token
PATCH http://localhost:3000/api/images/69ace105da34209d3166e9f6
Content-Type: application/json
Authorization: Bearer REPLACE_WITH_NON_OWNER_JWT

{
  "name": "i'm going to fail!"
}

### Rename image bad request
PATCH http://localhost:3000/api/images/69ace105da34209d3166e9f6
Content-Type: application/json
Authorization: Bearer REPLACE_WITH_JWT

{
  "title": "i'm a bad request!"
}

### Rename image not found
PATCH http://localhost:3000/api/images/000000000000000000000000
Content-Type: application/json
Authorization: Bearer REPLACE_WITH_JWT

{
  "name": "name"
}

### Rename image too large, over 100 chars
PATCH http://localhost:3000/api/images/69ace105da34209d3166e9f6
Content-Type: application/json
Authorization: Bearer REPLACE_WITH_JWT

{
  "name": "iamwaytoooooooooooooooooooooooooooooooooooooooooooooooooooooloooooooooooooooooooooooooooooooonggggggggggggg"
}

### Register user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.com",
  "password": "password"
}

### Register duplicate username
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "test",
  "email": "another@test.com",
  "password": "password"
}

### Register user with bad data
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "test"
}

### Login success
POST http://localhost:3000/api/auth/tokens
Content-Type: application/json

{
  "username": "test",
  "password": "password"
}

### Login bad request
POST http://localhost:3000/api/auth/tokens
Content-Type: application/json

{
  "username": "test"
}

### Login with incorrect password
POST http://localhost:3000/api/auth/tokens
Content-Type: application/json

{
  "username": "test",
  "password": "wrongpassword"
}

### Login unknown user
POST http://localhost:3000/api/auth/tokens
Content-Type: application/json

{
  "username": "dne",
  "password": "password"
}
